export const state = {
  scene: null,
  camera: null,
  renderer: null,
  controls: null,
  activeMesh: null,
  activeWireframe: null,
  activeSlices: [],
  layerSegments: [],
  activeToolpaths: [],
  gridHelper: null,
  ambientLight: null,
  cameraLight: null,
  dirLight: null,
  raycaster: null,
  mouse: null,
  selectionMesh: null,
  mouseDownTime: 0,
  pointerDownX: 0,
  pointerDownY: 0,
  sliceAxis: null,
  toolMesh: null,
  toolRadius: null,
  boundaryConnectors: null,
  contours: [],
  boundaryPoints: [],
  contoursAndBoundaryPoints: [],
  toolPaths: [],
  gcodeVisualization: null,
};

export const config = {
  renderMode: 'both',
  showGrid: true,
  showBoundaryConnectors: true,
  showStlMesh: true,
  showToolMesh: true,
  showSlices: true,
  showToolpaths: true,
  showGcodePath: true,
};
